@startuml Editar gasto

|Sistema|
start
:Iniciar edición de gasto;
:El usuario ingresa la fecha del gasto a editar;
|Servidor|
:Buscar gasto en el sistema;
if (¿Gasto encontrado?) then (si)
    |Sistema|
    :Mostrar datos actuales del gasto;
    :El usuario modifica la fecha del gasto;
    :El usuario modifica el total del gasto;
    :El usuario modifica la descripción del gasto;
    :El usuario modifica la categoría del gasto;
    :Validar datos modificados;
    if (Datos válidos?) then (si)
        |Servidor|
        :Guardar cambios en el sistema;
        |Sistema|
        :Mostrar mensaje de confirmación de edición;
    else (no)
        :Mostrar mensaje de error;
    endif
else (no)
    :Mostrar mensaje de error;
endif
:Finalizar edición de gasto;
stop

@enduml
