@startuml Generar reporte

|Sistema|
start
:Iniciar creación de reporte;
if (¿El usuario selecciona un reporte entre dos fechas?) then (si)
    :El usuario ingresa las fechas de inicio y fin del reporte;
endif
:El usuario selecciona el tipo de reporte (financiero o de productos);
if (¿El usuario selecciona un reporte financiero?) then (si)
    :Mostrar opciones de reporte financiero (ingresos, gastos, ingresos contra gastos);

else (no)
    :Mostrar opciones de reporte de productos (productos, envíos entre sucursales, productos más comprados);
endif
|Servidor|
:Cargar información para el reporte;

|Sistema|
:Generar el reporte seleccionado;
:Mostrar el reporte en pantalla;
:Finalizar creación de reporte;
stop

@enduml
